[package]
name = "pingdown"
version = "1.1.3"
authors = ["Chris233 h-chris233@qq.com"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/H-Chris233/pingdown/"
default-run = "pingdown"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
regex = "1.11.1"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
