[package]
name = "pingdown"
version = "1.1.2"
authors = ["Chris233 h-chris233@qq.com"]
edition = "2021"
readme = "README.md"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
regex = "1.11.1"
